url: http://www.librenms.org
baseurl: 

# Site settings
title: LibreNMS
description: "LibreNMS is an autodiscovering PHP/MySQL-based network monitoring system."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: da223a
  secondary: c91028
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/librenms
  - title: facebook-official
    url: https://www.facebook.com/LibreNMS
  - title: google-plus
    url: https://plus.google.com/u/1/communities/111170344284862070465
  - title: github
    url: https://github.com/librenms/librenms

# Build settings
permalink: pretty
gems:
  - jekyll-redirect-from
